### ISSUE TITLE
OWL Features Supported by ELK - Wiki not up to date; Which parts of OWL-EL are currently not supported?

### ISSUE THREAD

**Issue by gnu9** [liveontologies/elk-reasoner#44]
ELK supports supports ObjectPropertyRange according to @ykazakov in the google-group discussion [Elk plans?](https://groups.google.com/d/msg/elk-reasoner-discussion/Yp_1UKheL0M/dNt6RdaGqu8J), but this isn't mentioned in [wiki/OwlFeatures](https://github.com/liveontologies/elk-reasoner/wiki/OwlFeatures).

It would be interesting and helpful to know which OWL2 features are
* fully supported,
* supported with (these ... ) limitations,
* completely unsupported.

Especially, which parts of OWL-EL are currently not supported, which have limited support?
E.g. there is some code for ObjectHasSelf in the repository, but is it a limited support or full support?

Background: Some part of OWL-EL still seems to be unimplemented as the classification of my OWL-EL ontology is incomplete. It contains concept-cross-products simulated through rolification via ObjectHasSelf, ObjectPropertyDomain, ObjectPropertyRange, owl:topObjectProperty and SubObjectPropertyOf( ObjectPropertyChain(...) ... ). I guess not all of this is implemented yet?

**Comment by ykazakov** [comment]
The wiki page refers to the latest *released* version of ELK (currently 0.4.3).
The discussion at the google group refers to the features from the upcoming (rather overdue) release. 

Regarding your other questions, ELK usually provides warnings when some features are not supported (and ignored), unless logging is disabled. Particularly, it should tell that ObjectHasSelf are ignored. It is used internally for translation of reflexive object properties for which only positive occurrence of ObjectHasSelf are sufficient. ObjectPropertyRange should work if you do not have nominals or individuals and if the role chain axioms satisfy the [global restrictions for EL](https://www.w3.org/TR/owl2-profiles/#Global_Restrictions). This is currently not verified, so no warning is issued. If you sketch your translation, I can tell you what currently works and what does not.

**Comment by gnu9** [comment]
My fault, I didn't notice that the attatched ELK is a 0.5 snapshot. Is it planned to release 0.5 this year?

ELK 0.4.3 warns me that it doesn't support ObjectHasSelf, ObjectPropertyRange, DataPropertyRange and DataSomeValuesFrom; I wasn't sure if some of the warnings are misleading because I assumed that ObjectPropertyRange is already supported.

The rolifications that I use are like this:
```
EquivalentClasses(:A ObjectHasSelf(:A__R))
ObjectPropertyDomain(:A__R :A)
ObjectPropertyRange(:A__R :A)
```
A cross-product of classes A and B looks like this:
```
SubObjectPropertyOf(ObjectPropertyChain(:A__R owl:topObjectProperty :B__R) :OP)
```

Using ObjectHasSelf in an equivalence would not work in ELK 0.5 as well? But it does support this positive use `SubClassOf(:A  ObjectHasSelf(:A__R))`?

I did respect the global restrictions as they are stated in Pushing the EL Envelope (Baader et al. 2005) and Pushing the EL Envelope further (Baader et al. 2008) and ObjectHasSelf isn't applied on non-simple object properties (e.g. there is no `SubObjectPropertyOf( ObjectPropertyChain( :OPE1 ... :OPEn ) :A__R )` , also not indirectly). I did purposley not respect the OWL-EL limitations on Datatypes because I prefered to drop support for integer numbers in favor of `:DT <q` and `:DT =q` on the rationals (*) which is permitted in EL++ (Baader et al. 2005).

I couldn't test the elk-distribution-0.5.0-SNAPSHOT-15-05-15-protege-plugin from the google group ("Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/maven/artifact/versioning/ComparableVersion" - I did use Protege 5.1, not Protege 5 beta) and haven't yet build it from current sources to test it.

(*) I am using three patterns that can be expressed as `∃ :DT <q` (`<q(:DT)` when written as in (Baader et al. 2005)) or as `∃ :DT =q`, e.g. in these examples:
```
DataSomeValuesFrom( :DT DatatypeRestriction( owl:rational xsd:maxExclusive "63/1"^^owl:rational) )
≡ (∃ :DT <63/1)
DataSomeValuesFrom( :DT DataOneOf( "15/1"^^owl:rational ) )
≡ (∃ :DT =15/1)
DataPropertyRange( :DT DatatypeRestriction( owl:rational xsd:minInclusive "0/1"^^owl:rational ) )
⇔ (∃ :DT <0/1) ⊑ ⊥
```
I added FunctionalDataProperty(:DT) for any such datatype, because the feature names of the concrete domain (:DT here, f_i in the paper) are interpreted as partial functions in (Baader et al. 2005). Although it is feasible in EL++, I am not using `:DT1 + :DT2` as this is already in the scope of the OWL2 DataRangeExtension and I don't know any non-commercial OWL reasoner that supports this.

**Comment by ykazakov** [comment]
- the [current features](https://github.com/liveontologies/elk-reasoner/wiki/OwlFeatures), which apply to ELK 0.4.3, do not mention ObjectPropertyRange. Hence is the warning.
- you can obtain the latest development version of elk as described [here](https://github.com/liveontologies/elk-reasoner/wiki/GettingElk), but there is no documentation. As a rule of thumb, if ELK does not complain, it should compute all subsumptions correctly.
- ObjectHasSelf is not yet supported even in the development version (but ReflexiveObjectProperty is)
- the [global restrictions for OWL2 EL profile](https://www.w3.org/TR/owl2-profiles/#Global_Restrictions) are not about simple roles or datatypes. They are about a combined usage of ObjectPropertyChain, SubObjectPropertyOf, and ObjectPropertyRange axioms.
- owl:topObjectProperty is not supported in negative positions (on the left-hand side of axioms, like in your encoding of cross-product). I think ELK should complain, but if not, this should be fixed. I am afraid, it will not be possible to express cross-products using the features supported in ELK. Without going into lengthy technical details, the main reason is that such constructors are not "local", i.e., they depend on whether existence of an instance of one class expression causes the existence of an instance of another class expressions.
- datatypes are currently not supported in ELK (except for some "trivial" cases of ObjectHasValue). I do not think that they are going to be supported in a distant future.

**Comment by gnu9** [comment]
* Neither ELK 0.4.3 nor ELK 0.5.0-SNAPSHOT complain about my use of owl:topObjectProperty in negative positions.
* Using DataHasValue(:DT val) instead of DataSomeValuesFrom( :DT DataOneOf( val ) ) results in the appropriate warning that "ELK supports DataHasValue only partially" for 0.4.3 and 0.5.0, but 0.5.0 also warns "ELK does not support DataProperty. Axiom ignored: Declaration" which should rather be a warning that use of the declaration is restricted to DataHasValue. The other 0.5.0 warnings about Datatype and AnnotationProperty declarations make sense.
* The OWL 2 EL global restrictions are the syntactic restriction from section 3 in Pusing the EL Envelope Further (Baader et al. 2008), i.e. about the use of ObjectPropertyRange for :OP in ```SubObjectPropertyOf( ObjectPropertyChain( :OPE1 ... :OPEn ) :OP )``` _and in addition_ those of Section 11 of the OWL 2 structural specification, which boil down in case of OWL 2 EL to ObjectHasSelf isn't applied on non-simple object properties; my ontology respects both. I deliberatly exploit that "the existence of an instance of one class expression causes the existence of an instance of another class expressions" in the domain of the concept cross products, but take care that range(:OP) ⊑ C ⇒ range(:OPn) ⊑ C is asserted for ObjectPropertyChain inclusions to avoid the non-locality in the range. It's nonetheless a powerfull construction! But there seems to be no OWL 2 EL reasoner that supports these OWL 2 EL constructions, the only reasoner that I was able to use successfully is HermiT, and even with HermiT I need to add superfluous individuals in order to get a complete classification. Maybe I give MORe a try if I really need a speedup over HermiT.

**Comment by ykazakov** [comment]
Thank you for your report about missing and erroneous warnings. I will create a separate tickets for them (if not forget).

Regarding the simple role restriction, it is not currently relevant since ELK does not support ObjectHasSelf. But probably it also applies to reflexive roles, I will need to check.
The problem with verifying these kind of restrictions is that it involves checking several axioms at the same time and cannot be done while parsing the ontology, which is currently done. ELK does not remember axioms parsed, so it will be tricky to report violations of these conditions.

Can you briefly explain what you try to model using the cross-product? It is not often that someone requests such a feature (hence the lack of implementation).
